name: "Continuous Integration"

on:
  pull_request:
  push:

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: zip

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Update dependencies with composer (PHP < 8.0)"
        run: "composer update --no-interaction --no-progress --no-suggest"
        if: matrix.php-version != 8.0

      # Required as php-cs-fixer can't be used yet on PHP 8.0
      - name: "Update dependencies with composer (PHP 8.0)"
        run: "composer update --no-interaction --no-progress --no-suggest --ignore-platform-req=php"
        if: matrix.php-version == 8.0

      - name: "Run PHPUnit"
        run: "vendor/bin/simple-phpunit"
